# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O39zTK_uXiNiFO_DOE3q1F7VolWptIJb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set plotting style for professional look
sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

# Load the dataset
df = pd.read_excel("Dataset for Data Analytics.xlsx")

# Display first few records
print("--- FIRST 5 ROWS ---")
display(df.head())

print("--- DATASET SUMMARY INFO ---")
df.info()

# Check for missing values
print("\n--- MISSING VALUES BEFORE CLEANING ---")
print(df.isnull().sum())

# Handle data cleaning tasks
# 1. Convert Date column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# 2. Fill missing Coupon Code records with 'NO_COUPON'
df['CouponCode'] = df['CouponCode'].fillna('NO_COUPON')

print("\n--- MISSING VALUES AFTER CLEANING ---")
print(df.isnull().sum())

# Generate basic summary statistics for numerical metrics
print("--- DESCRIPTIVE STATISTICS FOR NUMERICAL METRICS ---")
display(df[['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']].describe())

# 1. Product Analysis (Sorted by Total Revenue)
product_analysis = df.groupby('Product').agg(
    Quantity_Sold=('Quantity', 'sum'),
    Total_Revenue=('TotalPrice', 'sum'),
    Average_UnitPrice=('UnitPrice', 'mean'),
    Order_Count=('OrderID', 'count')
).sort_values(by='Total_Revenue', ascending=False)

print("--- PRODUCT PERFORMANCE ANALYSIS ---")
display(product_analysis)

# 2. Payment Method Popularity
payment_analysis = df.groupby('PaymentMethod').agg(
    Order_Count=('OrderID', 'count'),
    Total_Revenue=('TotalPrice', 'sum')
).sort_values(by='Total_Revenue', ascending=False)

print("\n--- PAYMENT METHOD ANALYSIS ---")
display(payment_analysis)

# 3. Referral Source Success
referral_analysis = df.groupby('ReferralSource').agg(
    Order_Count=('OrderID', 'count'),
    Total_Revenue=('TotalPrice', 'sum')
).sort_values(by='Total_Revenue', ascending=False)

print("\n--- REFERRAL SOURCE ANALYSIS ---")
display(referral_analysis)

# Ensure figures don't clip text
plt.tight_layout()

# 1. Product Revenue Distribution (Sorted Order)
plt.figure(figsize=(10, 5))
sns.barplot(data=product_analysis.reset_index(), x='Product', y='Total_Revenue', palette='Blues_r')
plt.title('Total Revenue Contribution by Product', fontsize=14, fontweight='bold')
plt.xlabel('Product Category')
plt.ylabel('Total Revenue ($)')
plt.savefig('product_revenue.png', bbox_inches='tight')
plt.show()

# 2. Monthly Sales Trend Over Time
df['YearMonth'] = df['Date'].dt.to_period('M')
monthly_sales = df.groupby('YearMonth')['TotalPrice'].sum().reset_index()
monthly_sales['YearMonth'] = monthly_sales['YearMonth'].astype(str)

plt.figure(figsize=(14, 5))
sns.lineplot(data=monthly_sales, x='YearMonth', y='TotalPrice', marker='o', color='crimson', linewidth=2)
plt.xticks(rotation=45)
plt.title('Monthly Sales Performance Trend (2023 - 2025)', fontsize=14, fontweight='bold')
plt.xlabel('Timeline (Year-Month)')
plt.ylabel('Total Sales Revenue ($)')
plt.savefig('monthly_sales_trend.png', bbox_inches='tight')
plt.show()

# 3. Order Status Proportions
plt.figure(figsize=(6, 6))
status_counts = df['OrderStatus'].value_counts()
plt.pie(status_counts, labels=status_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title('Order Status Distribution Breakup', fontsize=14, fontweight='bold')
plt.savefig('order_status_pie.png', bbox_inches='tight')
plt.show()

# Using the Interquartile Range (IQR) method to find revenue outliers
Q1 = df['TotalPrice'].quantile(0.25)
Q3 = df['TotalPrice'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['TotalPrice'] < lower_bound) | (df['TotalPrice'] > upper_bound)]

# Visualizing Outliers using Box Plot
plt.figure(figsize=(8, 4))
sns.boxplot(x=df['TotalPrice'], color='lightgreen')
plt.title('Box Plot for Order Total Prices (Outlier Detection)', fontsize=14, fontweight='bold')
plt.xlabel('Total Price Value ($)')
plt.savefig('total_price_boxplot.png', bbox_inches='tight')
plt.show()

print(f"Interquartile Range Boundaries:")
print(f"Lower Bound Threshold: {lower_bound:.2f}")
print(f"Upper Bound Threshold: {upper_bound:.2f}")
print(f"Total Number of Outlier Orders Detected: {len(outliers)}")
print("\n--- TOP OUTLIER TRANSACTIONS ---")
display(outliers[['OrderID', 'Product', 'Quantity', 'UnitPrice', 'TotalPrice']].head(10))